baseURL = "https://iamchristian.me/"
languageCode = "en-us"
title = "Christian Mendoza / Aspiring Data Analyst"
googleAnalytics = "G-6LJDRPG2BH"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
copyright = "&copy; Christian Mendoza. Built with [Hugo](//gohugo.io). [[source](//github.com/christianmendoza/iamchristian.me)]"
enableRobotsTXT = true
verbose = true
verboseLog = true
watch = true

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # METADATA
  name = "Christian Mendoza"
  subheadline = "Aspiring Data Analyst"
  blurb = "Organizing messy data into insightful data visualizations, uncovering patterns and trends, and drawing meaningful conclusions."
  description = "Christian Mendoza is an aspiring data analyst—organizing data, uncovering patterns and insights, and drawing meaningful conclusions."
  image = "/assets/images/christian-headshot.jpg"
  socialImage = "/assets/images/social-headshot.jpg"
  email = "me/iamchristian/christian"
  emailLabel = "Email"

  # SOCIALS
  [[params.social]]
    label = "R&eacute;sum&eacute;"
    icon = "pdf"
    url = "/resume"
    show = true

  [[params.social]]
    label = "Projects"
    icon = "folder-alt"
    url = "/projects"
    show = false

  [[params.social]]
    label = "LinkedIn"
    icon = "linkedin"
    url = "//linkedin.com/in/christianmendoza"
    show = true

  [[params.social]]
    label = "GitHub"
    icon = "github"
    url = "//github.com/christianmendoza"
    show = true

  [[params.social]]
    label = "Kaggle"
    icon = "kaggle"
    url = "//www.kaggle.com/iamchristianmendoza"
    show = false

  [[params.social]]
    label = "Tableau"
    icon = "tableau"
    url = "//public.tableau.com/profile/christian.mendoza"
    show = true
