baseURL = "https://iamchristian.me/"
languageCode = "en-us"
title = "Christian Mendoza / Technical Support Engineer"
googleAnalytics = "UA-82162805-1"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
copyright = "&copy; Christian Mendoza. Built with [Hugo](//gohugo.io). [[source](//github.com/christianmendoza/iamchristian.me)]"
enableRobotsTXT = true
verbose = true
verboseLog = true
watch = true

[markup]
  defaultMarkdownHandler = "blackfriday"

[params]
  # METADATA
  name = "Christian Mendoza"
  description = "Christian Mendoza is an experienced technical support engineer—researching, diagnosing, troubleshooting, and identifying solutions to resolve technical issues."
  socialImage = "/assets/images/social-headshot.jpg"
